-- Create the kiosk-slides storage bucket (private for signed URL access)
-- This migration creates the storage bucket and sets up RLS policies

-- Create the storage bucket
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'kiosk-slides',
  'kiosk-slides',
  false, -- Private bucket - requires signed URLs for access
  10485760, -- 10MB limit
  ARRAY['image/png', 'image/jpeg', 'image/jpg', 'image/webp']::text[]
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Policy: Allow authenticated users to upload to their own folder
CREATE POLICY "Users can upload kiosk slides to their folder"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'kiosk-slides' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- Policy: Allow users to update their own files
CREATE POLICY "Users can update their own kiosk slides"
ON storage.objects
FOR UPDATE
TO authenticated
USING (
  bucket_id = 'kiosk-slides' AND
  (storage.foldername(name))[1] = auth.uid()::text
)
WITH CHECK (
  bucket_id = 'kiosk-slides' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- Policy: Allow users to delete their own files
CREATE POLICY "Users can delete their own kiosk slides"
ON storage.objects
FOR DELETE
TO authenticated
USING (
  bucket_id = 'kiosk-slides' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- Policy: Allow users to read their own files
CREATE POLICY "Users can read their own kiosk slides"
ON storage.objects
FOR SELECT
TO authenticated
USING (
  bucket_id = 'kiosk-slides' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- Note: For public kiosk viewing, we use signed URLs generated by the service role
-- This bypasses RLS and provides time-limited access to images
